name: kairos
services:
  gotrain:
    image: rijdendetreinen/gotrain
    environment:
      - API_ADDRESS=:8080
      - SOURCE_SERVER=tcp://pubsub.besteffort.ndovloket.nl:7664
      - SOURCE_ENVELOPES_ARRIVALS=/RIG/InfoPlusDASInterface4
      - SOURCE_ENVELOPES_DEPARTURES=/RIG/InfoPlusDVSInterface4
      - SOURCE_ENVELOPES_SERVICES=/RIG/InfoPlusRITInterface5
    ports:
      - 8081:8080
  rendering:
    image: ghcr.io/emmaknijn/kairos-rendering:latest
    ports:
    - 3000:3000
  router:
    image: kairos-router
    build: ./router/
    ports:
      - 80:80
    depends_on:
      - rendering